#line 2 "../../../lib/srchilite/outlangdefscanner.cc"

#line 4 "../../../lib/srchilite/outlangdefscanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer outlangdef__create_buffer
#define yy_delete_buffer outlangdef__delete_buffer
#define yy_flex_debug outlangdef__flex_debug
#define yy_init_buffer outlangdef__init_buffer
#define yy_flush_buffer outlangdef__flush_buffer
#define yy_load_buffer_state outlangdef__load_buffer_state
#define yy_switch_to_buffer outlangdef__switch_to_buffer
#define yyin outlangdef_in
#define yyleng outlangdef_leng
#define yylex outlangdef_lex
#define yylineno outlangdef_lineno
#define yyout outlangdef_out
#define yyrestart outlangdef_restart
#define yytext outlangdef_text
#define yywrap outlangdef_wrap
#define yyalloc outlangdef_alloc
#define yyrealloc outlangdef_realloc
#define yyfree outlangdef_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE outlangdef_restart(outlangdef_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int outlangdef_leng;

extern FILE *outlangdef_in, *outlangdef_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up outlangdef_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up outlangdef_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via outlangdef_restart()), so that the user can continue scanning by
	 * just pointing outlangdef_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when outlangdef_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int outlangdef_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow outlangdef_wrap()'s to do buffer switches
 * instead of setting up a fresh outlangdef_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void outlangdef_restart (FILE *input_file  );
void outlangdef__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE outlangdef__create_buffer (FILE *file,int size  );
void outlangdef__delete_buffer (YY_BUFFER_STATE b  );
void outlangdef__flush_buffer (YY_BUFFER_STATE b  );
void outlangdef_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void outlangdef_pop_buffer_state (void );

static void outlangdef_ensure_buffer_stack (void );
static void outlangdef__load_buffer_state (void );
static void outlangdef__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER outlangdef__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE outlangdef__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE outlangdef__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE outlangdef__scan_bytes (yyconst char *bytes,int len  );

void *outlangdef_alloc (yy_size_t  );
void *outlangdef_realloc (void *,yy_size_t  );
void outlangdef_free (void *  );

#define yy_new_buffer outlangdef__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        outlangdef_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            outlangdef__create_buffer(outlangdef_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        outlangdef_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            outlangdef__create_buffer(outlangdef_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define outlangdef_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *outlangdef_in = (FILE *) 0, *outlangdef_out = (FILE *) 0;

typedef int yy_state_type;

extern int outlangdef_lineno;

int outlangdef_lineno = 1;

extern char *outlangdef_text;
#define yytext_ptr outlangdef_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up outlangdef_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	outlangdef_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[282] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,   56,    1,   55,
        2,   37,    3,   36,   35,   34,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,    4,    5,    2,   42,   43,    2,   42,   41,
       42,   57,    2,   57,    1,   44,    3,   50,   57,   54,
        2,   53,   54,   49,    2,   49,   48,   45,   49,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       40,   39,    0,    0,    0,   52,   51,   47,   46,   33,

       33,   33,   33,   33,   33,   33,   30,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,    0,   32,   30,   33,   33,   33,   10,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   38,   33,   29,   33,   17,
       33,   33,   33,   14,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   21,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   16,
       33,   18,   33,   33,   33,   33,   11,   27,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   15,
       33,   33,   31,   33,   33,   33,   13,   19,   33,   33,
       33,   33,   33,   33,   33,   33,   20,   33,   33,   33,
       33,   33,   25,   33,   33,   33,   12,   33,   33,   26,
       33,   33,   33,   33,   33,   33,    7,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       28,   33,    6,   33,   33,   33,    8,   33,   33,   33,
        9,   33,   33,   33,   22,   33,   33,   24,   33,   23,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    1,    9,   10,
       11,   12,   13,   14,    1,   15,    1,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,    1,    1,
       17,    1,   18,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       20,   21,   22,   23,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   19,   19,   34,   35,   36,
       37,   38,   19,   39,   40,   41,   42,   19,   19,   43,
       44,   19,   45,   46,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    3,    1,
        1,    1,    1,    4,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[291] =
    {   0,
        0,    0,   45,   47,   49,   53,   56,   57,   73,  101,
       62,   64,  128,  173,   82,   87,  369,  370,  370,  370,
      370,  370,  370,  370,  370,  370,    0,  332,   80,  330,
       35,   54,  333,   58,  332,  327,  327,  325,  332,  319,
      320,  322,  370,  370,  370,  370,  370,  370,  370,  370,
       75,  370,  370,    0,  370,  370,  370,  370,  321,  370,
      370,  370,   91,  370,  370,  370,  370,  370,   92,    0,
      329,  324,  327,  319,  318,  321,  323,  321,  307,  304,
       87,  321,  309,   87,  315,  303,  312,  297,  315,  311,
      370,  370,    0,  332,  309,  370,  370,  370,  370,  304,

      302,  297,  305,  295,  306,  289,    0,  300,  299,  293,
      293,  291,  295,  286,  292,  281,  279,  290,  284,  281,
      287,    0,  370,  370,  278,  278,  279,    0,  273,  269,
      281,  273,  280,  265,  270,  272,   84,  277,  270,  261,
       67,  262,  271,  259,  259,  370,  258,    0,  259,  260,
      260,  258,  252,    0,  263,  261,  262,  246,  248,  245,
      242,  240,  246,  249,  252,   83,  246,  245,    0,  239,
      252,  235,  237,  241,  244,  248,  231,  235,  240,  239,
      238,  232,  238,  228,  227,  233,  232,  235,  226,    0,
      220,    0,  223,  219,  114,  216,    0,    0,  224,  218,

      224,  222,  226,  220,  221,  209,  209,  176,  180,    0,
      190,  178,  370,  184,  179,  173,    0,    0,  171,  185,
      179,  182,  168,  172,  175,  162,    0,  172,  158,  166,
      170,  159,    0,  158,  158,  153,    0,  160,  158,    0,
      157,  150,  143,  146,  145,  133,    0,  129,  126,  137,
      135,  123,  122,  122,  132,  131,  120,  129,  120,  127,
        0,  119,    0,  125,  114,  113,    0,  120,  109,  115,
        0,  113,  110,   99,    0,  100,  100,    0,   97,    0,
      370,  220,  224,  228,  232,  236,  238,  242,  122,   66
    } ;

static yyconst flex_int16_t yy_def[291] =
    {   0,
      281,    1,  282,  282,  283,  283,  284,  284,  284,  284,
      285,  285,  286,  286,  284,  284,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  288,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      281,  281,  289,  288,  281,  281,  281,  281,  281,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  290,  281,  281,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  281,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  281,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
        0,  281,  281,  281,  281,  281,  281,  281,  281,  281
    } ;

static yyconst flex_int16_t yy_nxt[418] =
    {   0,
       18,   19,   20,   21,   19,   22,   23,   18,   18,   18,
       18,   18,   24,   25,   18,   18,   26,   18,   27,   18,
       18,   18,   18,   27,   28,   29,   30,   31,   32,   33,
       27,   27,   34,   35,   27,   36,   37,   38,   39,   40,
       41,   42,   27,   27,   18,   18,   18,   44,   45,   44,
       45,   47,   48,   49,   50,   47,   48,   49,   50,   53,
       53,   54,   54,   76,   52,   61,   52,   61,  146,   51,
       62,   77,   62,   51,   55,   20,   53,   55,   56,   57,
       91,   58,   63,   55,   63,   53,   55,   56,   55,   78,
       53,   55,   56,   81,  163,   92,   79,   98,   82,   96,

      164,   59,   55,   20,   53,   55,   56,   57,   72,   58,
       73,   97,   99,  110,  114,  213,   74,   93,  213,  158,
      111,  159,  186,  187,  122,  280,  279,  115,  278,   59,
       52,   65,   66,   67,  277,   68,  276,   68,   68,   68,
       68,  275,   68,  274,  273,   68,  272,   68,   69,   68,
       68,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,   68,   68,   68,   52,   65,   66,   67,  250,
       68,  249,   68,   68,   68,   68,  248,   68,  247,  246,
       68,  245,   68,   69,   68,   68,  244,  243,  242,  241,

      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,   68,   68,   68,
       43,   43,   43,   43,   46,   46,   46,   46,   52,   52,
       52,   52,   60,   60,   60,   60,   64,   64,   64,   64,
       70,   70,   94,  223,   94,   94,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,

      165,  162,  161,  160,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  121,  120,
      119,  118,  117,  116,  113,  112,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   95,   90,   89,   88,
       87,   86,   85,   84,   83,   80,   75,   71,  281,   17,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281
    } ;

static yyconst flex_int16_t yy_chk[418] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    4,
        4,    5,    5,    5,    5,    6,    6,    6,    6,    7,
        8,    7,    8,   31,   11,   11,   12,   12,  290,    5,
       11,   31,   12,    6,    9,    9,    9,    9,    9,    9,
       51,    9,   11,   15,   12,   15,   15,   15,   16,   32,
       16,   16,   16,   34,  141,   51,   32,   69,   34,   63,

      141,    9,   10,   10,   10,   10,   10,   10,   29,   10,
       29,   63,   69,   81,   84,  195,   29,   51,  195,  137,
       81,  137,  166,  166,  289,  279,  277,   84,  276,   10,
       13,   13,   13,   13,  274,   13,  273,   13,   13,   13,
       13,  272,   13,  270,  269,   13,  268,   13,   13,   13,
       13,  266,  265,  264,  262,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  246,  245,
      244,  243,   13,   13,   13,   14,   14,   14,   14,  242,
       14,  241,   14,   14,   14,   14,  239,   14,  238,  236,
       14,  235,   14,   14,   14,   14,  234,  232,  231,  230,

      229,  228,  226,  225,  224,  223,  222,  221,  220,  219,
      216,  215,  214,  212,  211,  209,  208,   14,   14,   14,
      282,  282,  282,  282,  283,  283,  283,  283,  284,  284,
      284,  284,  285,  285,  285,  285,  286,  286,  286,  286,
      287,  287,  288,  207,  288,  288,  206,  205,  204,  203,
      202,  201,  200,  199,  196,  194,  193,  191,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  168,  167,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  153,  152,  151,  150,  149,  147,  145,  144,  143,

      142,  140,  139,  138,  136,  135,  134,  133,  132,  131,
      130,  129,  127,  126,  125,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  106,
      105,  104,  103,  102,  101,  100,   95,   94,   90,   89,
       88,   87,   86,   85,   83,   82,   80,   79,   78,   77,
       76,   75,   74,   73,   72,   71,   59,   42,   41,   40,
       39,   38,   37,   36,   35,   33,   30,   28,   17,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int outlangdef__flex_debug;
int outlangdef__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *outlangdef_text;
#line 1 "../../../lib/srchilite/outlangdefscanner.ll"
#line 2 "../../../lib/srchilite/outlangdefscanner.ll"
/*
 * Copyright (C) 1999-2005, Lorenzo Bettini, http://www.lorenzobettini.it
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <sstream>
#include "outlangdefparser.h"
#include "outlangdefscanner.h"
#include "fileutil.h"
#include "ioexception.h"

#include <stack>
#include <stdlib.h>

using namespace srchilite;

//#define DEBUG_SCANNER
#ifdef DEBUG_SCANNER
#include <iostream> // for debug
#define DEB(s) std::cerr << s << std::endl;
#define DEB2(s,s2) std::cerr << s << ": " << s2 << std::endl;
#else
#define DEB(s)
#define DEB2(s,s2)
#endif

#define PUSH(s) yy_push_state(s);
#define POP() yy_pop_state();

static std::ostringstream buff;

static void buffer(const char *s);
static void buffer(const char c);
static void buffer_escape(const char *c);
static const std::string *flush_buffer();
static void open_include_file(const char *file);
static void close_include_file();

ParseStructPtr outlang_parsestruct;

typedef std::stack<ParseStructPtr> ParseStructStack;
static ParseStructStack parsestructstack;


#line 728 "../../../lib/srchilite/outlangdefscanner.cc"

#define INITIAL 0
#define COMMENT_STATE 1
#define STRING_STATE 2
#define INCLUDE_STATE 3
#define TRANSLATION_STATE 4
#define REGEX_STATE 5
#define LITERAL_STATE 6
#define TRANSLATED_STATE 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int outlangdef_lex_destroy (void );

int outlangdef_get_debug (void );

void outlangdef_set_debug (int debug_flag  );

YY_EXTRA_TYPE outlangdef_get_extra (void );

void outlangdef_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *outlangdef_get_in (void );

void outlangdef_set_in  (FILE * in_str  );

FILE *outlangdef_get_out (void );

void outlangdef_set_out  (FILE * out_str  );

int outlangdef_get_leng (void );

char *outlangdef_get_text (void );

int outlangdef_get_lineno (void );

void outlangdef_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int outlangdef_wrap (void );
#else
extern int outlangdef_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( outlangdef_text, outlangdef_leng, 1, outlangdef_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( outlangdef_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( outlangdef_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, outlangdef_in))==0 && ferror(outlangdef_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(outlangdef_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int outlangdef_lex (void);

#define YY_DECL int outlangdef_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after outlangdef_text and outlangdef_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 81 "../../../lib/srchilite/outlangdefscanner.ll"


#line 935 "../../../lib/srchilite/outlangdefscanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! outlangdef_in )
			outlangdef_in = stdin;

		if ( ! outlangdef_out )
			outlangdef_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			outlangdef_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				outlangdef__create_buffer(outlangdef_in,YY_BUF_SIZE );
		}

		outlangdef__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of outlangdef_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 282 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 370 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 83 "../../../lib/srchilite/outlangdefscanner.ll"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "../../../lib/srchilite/outlangdefscanner.ll"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "../../../lib/srchilite/outlangdefscanner.ll"
{ PUSH(COMMENT_STATE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "../../../lib/srchilite/outlangdefscanner.ll"
{}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 89 "../../../lib/srchilite/outlangdefscanner.ll"
{ ++(outlang_parsestruct->line);  POP(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "../../../lib/srchilite/outlangdefscanner.ll"
{ return NODOC_TEMPLATE_T ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "../../../lib/srchilite/outlangdefscanner.ll"
{ return DOC_TEMPLATE_T ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "../../../lib/srchilite/outlangdefscanner.ll"
{ return STYLE_TEMPLATE_T ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "../../../lib/srchilite/outlangdefscanner.ll"
{ return STYLE_SEPARATOR_T ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "../../../lib/srchilite/outlangdefscanner.ll"
{ return BOLD_T ; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "../../../lib/srchilite/outlangdefscanner.ll"
{ return ITALICS_T ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "../../../lib/srchilite/outlangdefscanner.ll"
{ return UNDERLINE_T ; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "../../../lib/srchilite/outlangdefscanner.ll"
{ return NOTFIXED_T ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "../../../lib/srchilite/outlangdefscanner.ll"
{ return FIXED_T ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "../../../lib/srchilite/outlangdefscanner.ll"
{ return COLORMAP_T ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "../../../lib/srchilite/outlangdefscanner.ll"
{ return BG_COLOR_T ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "../../../lib/srchilite/outlangdefscanner.ll"
{ return COLOR_T ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "../../../lib/srchilite/outlangdefscanner.ll"
{ return DEFAULT_T ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "../../../lib/srchilite/outlangdefscanner.ll"
{ return ONESTYLE_T ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "../../../lib/srchilite/outlangdefscanner.ll"
{ return EXTENSION_T ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "../../../lib/srchilite/outlangdefscanner.ll"
{ return ANCHOR_T ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "../../../lib/srchilite/outlangdefscanner.ll"
{ return INLINE_REFERENCE_T ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "../../../lib/srchilite/outlangdefscanner.ll"
{ return POSTLINE_REFERENCE_T ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 109 "../../../lib/srchilite/outlangdefscanner.ll"
{ return POSTDOC_REFERENCE_T ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 110 "../../../lib/srchilite/outlangdefscanner.ll"
{ return REFERENCE_T ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 111 "../../../lib/srchilite/outlangdefscanner.ll"
{ return LINE_PREFIX_T; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 112 "../../../lib/srchilite/outlangdefscanner.ll"
{ return LINENUM_T; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 113 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(TRANSLATION_STATE); return TRANSLATIONS_T ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 114 "../../../lib/srchilite/outlangdefscanner.ll"
{ return BEGIN_T ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 115 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(INITIAL); return END_T ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(INCLUDE_STATE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "../../../lib/srchilite/outlangdefscanner.ll"
{
  char *file_name = &outlangdef_text[1];
  file_name[strlen(file_name)-1] = '\0';

  try {
    open_include_file(file_name);
  } catch (IOException &e) {
    outlangdef_lval.string = new std::string(e.filename);
    return WRONG_INCLUDE_FILE;
  }

  outlangdef_push_buffer_state(outlangdef__create_buffer(outlangdef_in,YY_BUF_SIZE));

  BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_STATE):
case YY_STATE_EOF(STRING_STATE):
case YY_STATE_EOF(INCLUDE_STATE):
case YY_STATE_EOF(TRANSLATION_STATE):
case YY_STATE_EOF(REGEX_STATE):
case YY_STATE_EOF(LITERAL_STATE):
case YY_STATE_EOF(TRANSLATED_STATE):
#line 134 "../../../lib/srchilite/outlangdefscanner.ll"
{
  fclose(outlangdef_in);
  outlangdef_in = 0;
  outlangdef_pop_buffer_state();

  if ( !YY_CURRENT_BUFFER )
    {
      yyterminate();
    }
  else
    close_include_file();
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 147 "../../../lib/srchilite/outlangdefscanner.ll"
{ DEB2("KEY",outlangdef_text); outlangdef_lval.string = new std::string(outlangdef_text) ; return KEY ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "../../../lib/srchilite/outlangdefscanner.ll"
{ return '=' ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 149 "../../../lib/srchilite/outlangdefscanner.ll"
{ return ',' ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 150 "../../../lib/srchilite/outlangdefscanner.ll"
{ return '+' ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(STRING_STATE) ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 153 "../../../lib/srchilite/outlangdefscanner.ll"
{
  string s = &outlangdef_text[1];
  s = "0" + s;
  int i = strtol(s.c_str(), (char **)NULL, 0);
  buffer( (char)i ) ;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 159 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 160 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( "\"" ) ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 161 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(INITIAL) ; outlangdef_lval.string = flush_buffer() ; DEB2("STRINGDEF",outlangdef_lval.string); return STRINGDEF; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 162 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 163 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( "\n" ) ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 165 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(LITERAL_STATE) ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 166 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer_escape( outlangdef_text ) ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 167 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 168 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 169 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(TRANSLATION_STATE) ; outlangdef_lval.string = flush_buffer() ; DEB2("STRINGDEF",loutlangdef_lval.string); return REGEXDEF; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 170 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "../../../lib/srchilite/outlangdefscanner.ll"
{ BEGIN(REGEX_STATE) ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 173 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 174 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( "'" ) ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 175 "../../../lib/srchilite/outlangdefscanner.ll"
{
    BEGIN(TRANSLATED_STATE) ;
    // entering TRANSLATED_STATE makes sure that 'regex' is used only
    // for specifying the sequence to be translated, and not the translated sequence
    outlangdef_lval.string = flush_buffer() ;
    DEB2("STRINGDEF",outlangdef_lval.string); return REGEXDEF;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 182 "../../../lib/srchilite/outlangdefscanner.ll"
{  buffer( outlangdef_text ) ; }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 184 "../../../lib/srchilite/outlangdefscanner.ll"
{ DEB("NEWLINE"); ++(outlang_parsestruct->line) ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 186 "../../../lib/srchilite/outlangdefscanner.ll"
{ return outlangdef_text[0] ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 188 "../../../lib/srchilite/outlangdefscanner.ll"
ECHO;
	YY_BREAK
#line 1353 "../../../lib/srchilite/outlangdefscanner.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed outlangdef_in at a new source and called
			 * outlangdef_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = outlangdef_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( outlangdef_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * outlangdef_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of outlangdef_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					outlangdef_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			outlangdef_restart(outlangdef_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) outlangdef_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 282 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 282 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 281);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up outlangdef_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					outlangdef_restart(outlangdef_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( outlangdef_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve outlangdef_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void outlangdef_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        outlangdef_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            outlangdef__create_buffer(outlangdef_in,YY_BUF_SIZE );
	}

	outlangdef__init_buffer(YY_CURRENT_BUFFER,input_file );
	outlangdef__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void outlangdef__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		outlangdef_pop_buffer_state();
	 *		outlangdef_push_buffer_state(new_buffer);
     */
	outlangdef_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	outlangdef__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (outlangdef_wrap()) processing, but the only time this flag
	 * is looked at is after outlangdef_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void outlangdef__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	outlangdef_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE outlangdef__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) outlangdef_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in outlangdef__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) outlangdef_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in outlangdef__create_buffer()" );

	b->yy_is_our_buffer = 1;

	outlangdef__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with outlangdef__create_buffer()
 * 
 */
    void outlangdef__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		outlangdef_free((void *) b->yy_ch_buf  );

	outlangdef_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a outlangdef_restart() or at EOF.
 */
    static void outlangdef__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	outlangdef__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then outlangdef__init_buffer was _probably_
     * called from outlangdef_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void outlangdef__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		outlangdef__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void outlangdef_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	outlangdef_ensure_buffer_stack();

	/* This block is copied from outlangdef__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from outlangdef__switch_to_buffer. */
	outlangdef__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void outlangdef_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	outlangdef__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		outlangdef__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void outlangdef_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)outlangdef_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in outlangdef_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)outlangdef_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in outlangdef_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE outlangdef__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) outlangdef_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in outlangdef__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	outlangdef__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to outlangdef_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       outlangdef__scan_bytes() instead.
 */
YY_BUFFER_STATE outlangdef__scan_string (yyconst char * yystr )
{
    
	return outlangdef__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to outlangdef_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE outlangdef__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) outlangdef_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in outlangdef__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = outlangdef__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in outlangdef__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) outlangdef_alloc(new_size  );

		else
			(yy_start_stack) = (int *) outlangdef_realloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up outlangdef_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		outlangdef_text[outlangdef_leng] = (yy_hold_char); \
		(yy_c_buf_p) = outlangdef_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		outlangdef_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int outlangdef_get_lineno  (void)
{
        
    return outlangdef_lineno;
}

/** Get the input stream.
 * 
 */
FILE *outlangdef_get_in  (void)
{
        return outlangdef_in;
}

/** Get the output stream.
 * 
 */
FILE *outlangdef_get_out  (void)
{
        return outlangdef_out;
}

/** Get the length of the current token.
 * 
 */
int outlangdef_get_leng  (void)
{
        return outlangdef_leng;
}

/** Get the current token.
 * 
 */

char *outlangdef_get_text  (void)
{
        return outlangdef_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void outlangdef_set_lineno (int  line_number )
{
    
    outlangdef_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see outlangdef__switch_to_buffer
 */
void outlangdef_set_in (FILE *  in_str )
{
        outlangdef_in = in_str ;
}

void outlangdef_set_out (FILE *  out_str )
{
        outlangdef_out = out_str ;
}

int outlangdef_get_debug  (void)
{
        return outlangdef__flex_debug;
}

void outlangdef_set_debug (int  bdebug )
{
        outlangdef__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from outlangdef_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    outlangdef_in = stdin;
    outlangdef_out = stdout;
#else
    outlangdef_in = (FILE *) 0;
    outlangdef_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * outlangdef_lex_init()
     */
    return 0;
}

/* outlangdef_lex_destroy is for both reentrant and non-reentrant scanners. */
int outlangdef_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		outlangdef__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		outlangdef_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	outlangdef_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        outlangdef_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * outlangdef_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *outlangdef_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *outlangdef_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void outlangdef_free (void * ptr )
{
	free( (char *) ptr );	/* see outlangdef_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "../../../lib/srchilite/outlangdefscanner.ll"



void buffer(const char *s)
{
  buff << s;
}

void buffer(const char s)
{
  buff << s;
}

void buffer_escape(const char *s)
{
  buff << "\\" << s;
}

const std::string *flush_buffer()
{
  const std::string *ret = new std::string(buff.str());
  buff.str("");
  return ret;
}

void open_include_file(const char *name)
{
  string file_name = name;
  string path = outlang_parsestruct->path;

  if (! contains_path(name) &&
      contains_path(outlang_parsestruct->file_name))
    path = get_file_path(outlang_parsestruct->file_name);

  parsestructstack.push(outlang_parsestruct);
  outlang_parsestruct = ParseStructPtr(new ParseStruct(path, file_name));
  open_outlang_file_to_scan(path.c_str(), file_name.c_str());
}

void close_include_file()
{
  outlang_parsestruct = parsestructstack.top();
  parsestructstack.pop();
}


namespace srchilite {

void open_outlang_file_to_scan(const string &path, const string &name)
{
  outlangdef_in = open_data_file_stream(path, name);
}

void clear_outlangdefscanner() {
	//delete stringTable;
	outlangdef_lex_destroy();
}

void close_outlangdefinputfile() {
	// also close possible open files due to inclusions
	do {
	  if (outlangdef_in)
	  	fclose(outlangdef_in);
  	  outlangdef_pop_buffer_state();
    } while ( YY_CURRENT_BUFFER );
}

}

