#line 2 "../../../lib/srchilite/stylecssscanner.cc"

#line 4 "../../../lib/srchilite/stylecssscanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer stylecsssc__create_buffer
#define yy_delete_buffer stylecsssc__delete_buffer
#define yy_flex_debug stylecsssc__flex_debug
#define yy_init_buffer stylecsssc__init_buffer
#define yy_flush_buffer stylecsssc__flush_buffer
#define yy_load_buffer_state stylecsssc__load_buffer_state
#define yy_switch_to_buffer stylecsssc__switch_to_buffer
#define yyin stylecsssc_in
#define yyleng stylecsssc_leng
#define yylex stylecsssc_lex
#define yylineno stylecsssc_lineno
#define yyout stylecsssc_out
#define yyrestart stylecsssc_restart
#define yytext stylecsssc_text
#define yywrap stylecsssc_wrap
#define yyalloc stylecsssc_alloc
#define yyrealloc stylecsssc_realloc
#define yyfree stylecsssc_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE stylecsssc_restart(stylecsssc_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int stylecsssc_leng;

extern FILE *stylecsssc_in, *stylecsssc_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up stylecsssc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up stylecsssc_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via stylecsssc_restart()), so that the user can continue scanning by
	 * just pointing stylecsssc_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when stylecsssc_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int stylecsssc_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow stylecsssc_wrap()'s to do buffer switches
 * instead of setting up a fresh stylecsssc_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void stylecsssc_restart (FILE *input_file  );
void stylecsssc__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE stylecsssc__create_buffer (FILE *file,int size  );
void stylecsssc__delete_buffer (YY_BUFFER_STATE b  );
void stylecsssc__flush_buffer (YY_BUFFER_STATE b  );
void stylecsssc_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void stylecsssc_pop_buffer_state (void );

static void stylecsssc_ensure_buffer_stack (void );
static void stylecsssc__load_buffer_state (void );
static void stylecsssc__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER stylecsssc__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE stylecsssc__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE stylecsssc__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE stylecsssc__scan_bytes (yyconst char *bytes,int len  );

void *stylecsssc_alloc (yy_size_t  );
void *stylecsssc_realloc (void *,yy_size_t  );
void stylecsssc_free (void *  );

#define yy_new_buffer stylecsssc__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        stylecsssc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            stylecsssc__create_buffer(stylecsssc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        stylecsssc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            stylecsssc__create_buffer(stylecsssc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define stylecsssc_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *stylecsssc_in = (FILE *) 0, *stylecsssc_out = (FILE *) 0;

typedef int yy_state_type;

extern int stylecsssc_lineno;

int stylecsssc_lineno = 1;

extern char *stylecsssc_text;
#define yytext_ptr stylecsssc_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up stylecsssc_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	stylecsssc_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[274] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   32,   30,    1,    8,    2,    1,
        9,   30,   30,   31,    1,    2,    1,   31,    4,    1,
        5,    2,    1,    4,    6,   11,    7,   12,   29,    1,
        2,    1,   29,   29,   29,   29,   29,   27,    1,    1,
       15,   28,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   20,   20,   22,   22,   24,   24,   26,   26,    1,
        1,    3,    0,    7,    0,    0,    0,    0,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   20,    3,   22,    3,   24,    3,   26,    3,
        0,    0,    0,    0,    0,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   14,   15,   15,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       17,   18,   18,   10,    0,    0,    0,    0,   15,   15,
       15,   15,   15,   15,   15,   15,   18,   18,   18,   18,
       18,   18,   18,   18,    0,   13,    0,    0,   15,   15,
       15,   15,   15,   15,   15,   18,   18,   18,   18,   18,

       18,   18,    0,    0,    0,    0,    0,   15,   15,   15,
       15,   18,   18,   18,   18,    0,    0,    0,    0,    0,
       15,   15,   15,   15,   18,   18,   18,   18,    0,    0,
        0,    0,    0,   15,   15,   15,   18,   18,   18,    0,
        0,    0,    0,    0,   15,   15,   18,   18,    0,    0,
       21,    0,    0,   15,   15,   18,   18,    0,   23,   19,
        0,   15,   18,    0,    0,    0,    0,    0,    0,    0,
       25,   16,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    1,    1,    1,    1,
        1,    7,    1,    8,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
        1,    1,    1,    1,   15,   16,   15,   17,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   18,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   19,   15,
        1,    1,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   15,   30,   31,   32,   33,
       34,   35,   15,   36,   37,   38,   39,   15,   40,   41,
       42,   15,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[45] =
    {   0,
        1,    2,    2,    2,    2,    3,    1,    1,    1,    1,
        1,    4,    2,    2,    4,    4,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[290] =
    {   0,
        0,   21,    4,   16,   31,   36,   46,   50,   61,  105,
      148,  191,  235,    0,  279,    0,  322,  335,  348,  361,
      374,  387,  400,  413,  541,  542,  538,  542,  542,  534,
      542,  531,   10,  542,  535,  542,  531,  528,  542,  532,
      542,  542,  528,  525,  542,  542,    0,  542,  542,  529,
      542,  525,  522,  507,  493,  492,  500,  542,  522,  518,
        0,  542,   45,  480,  500,  484,  483,   17,  493,  492,
      491,    0,   46,  473,  493,  477,  476,   49,  486,  485,
      484,    0,  501,    0,  500,    0,  499,    0,  498,  502,
      498,  542,   62,    0,  479,  470,  467,  458,    0,   59,

       55,  474,  454,   62,  464,  447,  389,  399,  401,  390,
        0,   64,   61,  399,  383,   71,  391,  377,  373,  384,
      386,  375,    0,    0,    0,    0,    0,    0,    0,    0,
       78,  369,  363,  358,  357,  371,  368,  359,  344,  350,
      352,  339,  355,  340,  341,  335,    0,  338,  337,  344,
      335,  331,  317,  323,  325,  312,  322,  312,  314,  308,
        0,  311,  310,  542,  307,  296,  322,  321,  299,  300,
      201,   99,  200,  205,  200,  196,  198,  199,  193,  100,
      192,  197,  192,  188,  185,  542,   97,  196,  181,  187,
      180,  190,  187,  186,  170,  171,  177,  171,  181,  180,

      179,  163,  167,  179,  161,  173,  172,   66,  152,  165,
      165,   67,  149,  162,  161,  145,  151,  140,  152,  157,
      143,  142,  152,  151,  139,  137,  147,  144,  135,  138,
      135,  138,  130,  138,  141,  128,  135,  137,  124,  132,
      124,  129,  119,  110,  120,  111,  118,  109,  132,   98,
      542,  101,  117,  100,  105,   98,  103,  106,  542,  542,
       90,  100,   99,   68,   70,   60,   26,   25,   25,    9,
      542,  542,  542,  427,  432,  437,  442,  447,  452,  457,
      462,  467,  469,  472,  474,  478,  483,  488,  493
    } ;

static yyconst flex_int16_t yy_def[290] =
    {   0,
      274,  274,  275,  275,  276,  276,  275,  275,  277,  277,
      278,  278,  273,   13,  273,   15,  279,  279,  280,  280,
      281,  281,  282,  282,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  283,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      284,  273,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  286,  286,  287,  287,  288,  288,  289,  289,  273,
      273,  273,  273,  283,  273,  273,  273,  273,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  286,  286,  287,  287,  288,  288,  289,  289,
      273,  273,  273,  273,  273,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  273,  273,  273,  273,  273,  284,  284,
      284,  284,  284,  284,  284,  284,  285,  285,  285,  285,
      285,  285,  285,  285,  273,  273,  273,  273,  284,  284,
      284,  284,  284,  284,  284,  285,  285,  285,  285,  285,

      285,  285,  273,  273,  273,  273,  273,  284,  284,  284,
      284,  285,  285,  285,  285,  273,  273,  273,  273,  273,
      284,  284,  284,  284,  285,  285,  285,  285,  273,  273,
      273,  273,  273,  284,  284,  284,  285,  285,  285,  273,
      273,  273,  273,  273,  284,  284,  285,  285,  273,  273,
      273,  273,  273,  284,  284,  285,  285,  273,  273,  273,
      273,  284,  285,  273,  273,  273,  273,  273,  273,  273,
      273,  273,    0,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_nxt[587] =
    {   0,
      273,   27,   28,   29,   30,   35,   28,   36,   37,   31,
       32,  273,  273,  273,   38,   33,  273,   35,   28,   36,
       37,   33,   27,   28,   29,   30,   38,   93,  273,  273,
       31,   32,   40,   41,   42,   43,   33,   40,   41,   42,
       43,   44,   33,   93,  272,  106,   44,   35,   28,   36,
       37,   35,   28,   36,   37,  107,   38,  271,  270,  269,
       38,   34,   35,   28,   36,   37,   34,   34,   45,   34,
       46,   38,   34,   34,   34,  100,  112,  118,  131,  136,
      101,  113,  142,  138,  150,  131,  143,  119,  139,  152,
      268,  156,  221,  225,  153,  157,  164,  137,  267,  222,

      226,  266,  151,   48,   34,   34,   35,   28,   36,   37,
       34,   34,   45,   34,   46,   38,   34,   34,   34,  164,
      190,  197,  204,  161,  147,  191,  198,  265,  264,  263,
      161,  262,  147,  205,  192,  199,  206,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,   48,   34,   50,
       28,   51,   52,  251,  250,  249,  161,  248,   53,  247,
      147,  246,  245,  244,  243,  242,  241,  240,  239,   54,
       55,  161,  238,   56,  237,  236,  147,  235,  234,  233,
      232,  231,  230,  229,  161,   57,  228,  227,  147,  224,
      223,   58,   50,   28,   51,   52,  220,  219,  218,  217,

      216,   53,  161,  161,  161,  215,  214,  213,  212,  147,
      147,  147,   54,   55,  211,  210,   56,  209,  208,  207,
      203,  202,  201,  200,  161,  161,  196,  161,   57,  195,
      194,  193,  147,  147,   58,   34,   59,   28,   36,   60,
       61,   34,   34,   34,   34,   38,   61,   62,   62,   61,
       61,   61,   61,   61,   34,   61,   63,   64,   65,   61,
       61,   66,   61,   61,   61,   61,   61,   61,   67,   68,
       69,   61,   70,   61,   61,   61,   71,   34,   34,   34,
       59,   28,   36,   60,   72,   34,   34,   34,   34,   38,
       72,   62,   62,   72,   72,   72,   72,   72,   34,   72,

       73,   74,   75,   72,   72,   76,   72,   72,   72,   72,
       72,   72,   77,   78,   79,   72,   80,   72,   72,   72,
       81,   34,   34,   59,   28,   36,   60,  189,  147,  188,
      187,  186,   83,  185,   62,   62,   59,   28,   36,   60,
      184,  161,  183,  161,  182,   83,  181,   62,   62,   59,
       28,   36,   60,  161,  180,  161,  179,  178,   85,  161,
       62,   62,   59,   28,   36,   60,  177,  176,  147,  175,
      147,   85,  174,   62,   62,   59,   28,   36,   60,  173,
      147,  172,  147,  171,   87,  170,   62,   62,   59,   28,
       36,   60,  147,  169,  168,  167,  166,   87,  165,   62,

       62,   59,   28,   36,   60,  163,  162,  161,  160,  159,
       89,  158,   62,   62,   59,   28,   36,   60,  155,  154,
      149,  148,  147,   89,  146,   62,   62,   26,   26,   26,
       26,   26,   34,   34,   34,   34,   34,   39,   39,   39,
       39,   39,   47,   47,   47,   47,   47,   49,   49,   49,
       49,   49,   82,   82,   82,   82,   82,   84,   84,   84,
       84,   84,   86,   86,   86,   86,   86,   88,   88,   88,
       88,   88,   94,   94,   99,   99,  111,  111,  123,  145,
      123,  123,  123,  125,  144,  125,  125,  125,  127,  141,
      127,  127,  127,  129,  140,  129,  129,  129,  135,  134,

      133,  132,   91,   90,  130,  128,  126,  124,  122,  121,
      120,  117,  116,  115,  114,  110,  109,  108,  105,  104,
      103,  102,   91,   90,   98,   97,   96,   95,   92,   91,
       90,   92,   91,   90,   92,   91,   90,   92,   91,   90,
      273,   25,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_chk[587] =
    {   0,
        0,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    0,    0,    0,    3,    1,    0,    4,    4,    4,
        4,    1,    2,    2,    2,    2,    4,   33,    0,    0,
        2,    2,    5,    5,    5,    5,    2,    6,    6,    6,
        6,    5,    2,   33,  270,   68,    6,    7,    7,    7,
        7,    8,    8,    8,    8,   68,    7,  269,  268,  267,
        8,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   63,   73,   78,   93,  100,
       63,   73,  104,  101,  112,   93,  104,   78,  101,  113,
      266,  116,  208,  212,  113,  116,  131,  100,  265,  208,

      212,  264,  112,    9,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,  131,
      172,  180,  187,  263,  262,  172,  180,  261,  258,  257,
      256,  255,  254,  187,  172,  180,  187,  253,  252,  250,
      249,  248,  247,  246,  245,  244,  243,   10,   10,   11,
       11,   11,   11,  242,  241,  240,  239,  238,   11,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,   11,
       11,  227,  226,   11,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,   11,  214,  213,  211,  210,
      209,   11,   12,   12,   12,   12,  207,  206,  205,  204,

      203,   12,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,   12,   12,  192,  191,   12,  190,  189,  188,
      185,  184,  183,  182,  181,  179,  178,  177,   12,  176,
      175,  174,  173,  171,   12,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   17,   17,   17,   17,  170,  169,  168,
      167,  166,   17,  165,   17,   17,   18,   18,   18,   18,
      163,  162,  160,  159,  158,   18,  157,   18,   18,   19,
       19,   19,   19,  156,  155,  154,  153,  152,   19,  151,
       19,   19,   20,   20,   20,   20,  150,  149,  148,  146,
      145,   20,  144,   20,   20,   21,   21,   21,   21,  143,
      142,  141,  140,  139,   21,  138,   21,   21,   22,   22,
       22,   22,  137,  136,  135,  134,  133,   22,  132,   22,

       22,   23,   23,   23,   23,  122,  121,  120,  119,  118,
       23,  117,   23,   23,   24,   24,   24,   24,  115,  114,
      110,  109,  108,   24,  107,   24,   24,  274,  274,  274,
      274,  274,  275,  275,  275,  275,  275,  276,  276,  276,
      276,  276,  277,  277,  277,  277,  277,  278,  278,  278,
      278,  278,  279,  279,  279,  279,  279,  280,  280,  280,
      280,  280,  281,  281,  281,  281,  281,  282,  282,  282,
      282,  282,  283,  283,  284,  284,  285,  285,  286,  106,
      286,  286,  286,  287,  105,  287,  287,  287,  288,  103,
      288,  288,  288,  289,  102,  289,  289,  289,   98,   97,

       96,   95,   91,   90,   89,   87,   85,   83,   81,   80,
       79,   77,   76,   75,   74,   71,   70,   69,   67,   66,
       65,   64,   60,   59,   57,   56,   55,   54,   53,   52,
       50,   44,   43,   40,   38,   37,   35,   32,   30,   27,
       25,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int stylecsssc__flex_debug;
int stylecsssc__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *stylecsssc_text;
#line 1 "../../../lib/srchilite/stylecssscanner.ll"
#line 2 "../../../lib/srchilite/stylecssscanner.ll"
/*
 * Copyright (C) 1999-2007 Lorenzo Bettini, http://www.lorenzobettini.it
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdlib.h>
#include <string.h>

#include "stylekey.h"

#include "formatterfactory.h"
#include "stylecssparser.h"
#include <sstream>
#include "parsestyles.h"

using namespace srchilite;

static std::ostringstream buff;

extern int line ;

//#define DEBUG_SCANNER
#ifdef DEBUG_SCANNER
#include <iostream> // for debug
#define DEB(s) std::cerr << s << std::endl;
#define DEB2(s,s2) std::cerr << s << ": " << s2 << std::endl;
#else
#define DEB(s)
#define DEB2(s,s2)
#endif


#line 751 "../../../lib/srchilite/stylecssscanner.cc"

#define INITIAL 0
#define COMMENT_STATE 1
#define MULTI_COMMENT_STATE 2
#define STRING_STATE 3
#define CSS_SELECTOR 4
#define CSS_PROPERTIES 5
#define CSS_COLOR 6
#define CSS_BG_COLOR 7
#define CSS_FONT_WEIGHT 8
#define CSS_FONT_STYLE 9
#define CSS_FONT_FAMILY 10
#define CSS_TEXT_DECORATION 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int stylecsssc_lex_destroy (void );

int stylecsssc_get_debug (void );

void stylecsssc_set_debug (int debug_flag  );

YY_EXTRA_TYPE stylecsssc_get_extra (void );

void stylecsssc_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *stylecsssc_get_in (void );

void stylecsssc_set_in  (FILE * in_str  );

FILE *stylecsssc_get_out (void );

void stylecsssc_set_out  (FILE * out_str  );

int stylecsssc_get_leng (void );

char *stylecsssc_get_text (void );

int stylecsssc_get_lineno (void );

void stylecsssc_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int stylecsssc_wrap (void );
#else
extern int stylecsssc_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( stylecsssc_text, stylecsssc_leng, 1, stylecsssc_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( stylecsssc_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( stylecsssc_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, stylecsssc_in))==0 && ferror(stylecsssc_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(stylecsssc_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int stylecsssc_lex (void);

#define YY_DECL int stylecsssc_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after stylecsssc_text and stylecsssc_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 69 "../../../lib/srchilite/stylecssscanner.ll"


#line 952 "../../../lib/srchilite/stylecssscanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! stylecsssc_in )
			stylecsssc_in = stdin;

		if ( ! stylecsssc_out )
			stylecsssc_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			stylecsssc_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				stylecsssc__create_buffer(stylecsssc_in,YY_BUF_SIZE );
		}

		stylecsssc__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of stylecsssc_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 542 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "../../../lib/srchilite/stylecssscanner.ll"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "../../../lib/srchilite/stylecssscanner.ll"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "../../../lib/srchilite/stylecssscanner.ll"
{ BEGIN(MULTI_COMMENT_STATE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "../../../lib/srchilite/stylecssscanner.ll"
{}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 77 "../../../lib/srchilite/stylecssscanner.ll"
{ ++line;  BEGIN(INITIAL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "../../../lib/srchilite/stylecssscanner.ll"
{ return ',' ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "../../../lib/srchilite/stylecssscanner.ll"
{ stylecsssc_lval.string = new std::string(stylecsssc_text) ; return KEY ; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 83 "../../../lib/srchilite/stylecssscanner.ll"
{ ++line ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_SELECTOR) ;
  DEB("CSS SELECTOR");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_SELECTOR) ;
  DEB("BODY CSS SELECTOR");
  stylecsssc_lval.string = new std::string(stylecsssc_text) ;
  return KEY;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "../../../lib/srchilite/stylecssscanner.ll"
{
  // in case of comma separated selectors
  DEB("CSS SELECTOR");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 100 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  DEB("CSS PROPERTIES");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_COLOR);
  DEB("CSS COLOR");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  stylecsssc_lval.string = new std::string(stylecsssc_text) ;
  DEB2("CSS COLOR", stylecsssc_text);
  return COLOR ;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  DEB2("CSS COLOR", stylecsssc_text);
  /*
    we need to add the " in order to make source-highlight realize
    that this is a direct color specification
  */
  stylecsssc_lval.string = new std::string("\"" + std::string(stylecsssc_text) + "\"");
  return STRINGDEF;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 124 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_BG_COLOR);
  DEB("CSS BACKGROUND COLOR");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 128 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  stylecsssc_lval.string = new std::string(stylecsssc_text) ;
  DEB2("CSS BG COLOR", stylecsssc_text);
  return BG_COLOR ;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 134 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  DEB2("CSS BG COLOR", stylecsssc_text);
  /*
    we need to add the " in order to make source-highlight realize
    that this is a direct color specification
  */
  stylecsssc_lval.string = new std::string("\"" + std::string(stylecsssc_text) + "\"");
  return BG_STRINGDEF;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 144 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_FONT_WEIGHT);
  DEB("CSS FONT WEIGHT");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  if (strcmp(stylecsssc_text, "bold") == 0) {
    DEB("CSS BOLD");
    stylecsssc_lval.flag = srchilite::ISBOLD ;
    return BOLD ;
  }
  DEB2("discarding not handled value", stylecsssc_text);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 157 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_FONT_STYLE);
  DEB("CSS FONT STYLE");
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  if (strcmp(stylecsssc_text, "italic") == 0) {
    DEB("CSS ITALIC");
    stylecsssc_lval.flag = srchilite::ISITALIC ;
    return ITALICS ;
  }
  DEB2("discarding not handled value", stylecsssc_text);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 170 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_FONT_FAMILY);
  DEB("CSS FONT FAMILY");
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 174 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  if (strcmp(stylecsssc_text, "monospace") == 0) {
    DEB("CSS FIXED");
    stylecsssc_lval.flag = srchilite::ISFIXED ;
    return FIXED ;
  }
  DEB2("discarding not handled value", stylecsssc_text);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 183 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_TEXT_DECORATION);
  DEB("CSS TEXT DECORATION");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 187 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(CSS_PROPERTIES);
  if (strcmp(stylecsssc_text, "underline") == 0) {
    DEB("CSS UNDERLINE");
    stylecsssc_lval.flag = srchilite::ISUNDERLINE ;
    return UNDERLINE ;
  }
  DEB2("discarding not handled value", stylecsssc_text);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 196 "../../../lib/srchilite/stylecssscanner.ll"
{
  BEGIN(INITIAL);
  DEB("CSS END PROPERTIES");
  /*
    we must return ; since this is the terminator of a style option
    so we simulate it in case of css files
  */
  return ';' ;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 205 "../../../lib/srchilite/stylecssscanner.ll"
{
  /* discard other characters */
  DEB2("CSS discarding", stylecsssc_text);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 209 "../../../lib/srchilite/stylecssscanner.ll"
{
  /* discard other properties */
  DEB2("CSS PROPERTIES discarding", stylecsssc_text);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 214 "../../../lib/srchilite/stylecssscanner.ll"
{ return stylecsssc_text[0] ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 216 "../../../lib/srchilite/stylecssscanner.ll"
ECHO;
	YY_BREAK
#line 1298 "../../../lib/srchilite/stylecssscanner.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_STATE):
case YY_STATE_EOF(MULTI_COMMENT_STATE):
case YY_STATE_EOF(STRING_STATE):
case YY_STATE_EOF(CSS_SELECTOR):
case YY_STATE_EOF(CSS_PROPERTIES):
case YY_STATE_EOF(CSS_COLOR):
case YY_STATE_EOF(CSS_BG_COLOR):
case YY_STATE_EOF(CSS_FONT_WEIGHT):
case YY_STATE_EOF(CSS_FONT_STYLE):
case YY_STATE_EOF(CSS_FONT_FAMILY):
case YY_STATE_EOF(CSS_TEXT_DECORATION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed stylecsssc_in at a new source and called
			 * stylecsssc_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = stylecsssc_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( stylecsssc_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * stylecsssc_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of stylecsssc_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					stylecsssc_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			stylecsssc_restart(stylecsssc_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) stylecsssc_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 273);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up stylecsssc_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					stylecsssc_restart(stylecsssc_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( stylecsssc_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve stylecsssc_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void stylecsssc_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        stylecsssc_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            stylecsssc__create_buffer(stylecsssc_in,YY_BUF_SIZE );
	}

	stylecsssc__init_buffer(YY_CURRENT_BUFFER,input_file );
	stylecsssc__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void stylecsssc__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		stylecsssc_pop_buffer_state();
	 *		stylecsssc_push_buffer_state(new_buffer);
     */
	stylecsssc_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	stylecsssc__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (stylecsssc_wrap()) processing, but the only time this flag
	 * is looked at is after stylecsssc_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void stylecsssc__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	stylecsssc_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE stylecsssc__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) stylecsssc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in stylecsssc__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) stylecsssc_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in stylecsssc__create_buffer()" );

	b->yy_is_our_buffer = 1;

	stylecsssc__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with stylecsssc__create_buffer()
 * 
 */
    void stylecsssc__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		stylecsssc_free((void *) b->yy_ch_buf  );

	stylecsssc_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a stylecsssc_restart() or at EOF.
 */
    static void stylecsssc__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	stylecsssc__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then stylecsssc__init_buffer was _probably_
     * called from stylecsssc_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void stylecsssc__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		stylecsssc__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void stylecsssc_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	stylecsssc_ensure_buffer_stack();

	/* This block is copied from stylecsssc__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from stylecsssc__switch_to_buffer. */
	stylecsssc__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void stylecsssc_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	stylecsssc__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		stylecsssc__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void stylecsssc_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)stylecsssc_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in stylecsssc_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)stylecsssc_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in stylecsssc_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE stylecsssc__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) stylecsssc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in stylecsssc__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	stylecsssc__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to stylecsssc_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       stylecsssc__scan_bytes() instead.
 */
YY_BUFFER_STATE stylecsssc__scan_string (yyconst char * yystr )
{
    
	return stylecsssc__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to stylecsssc_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE stylecsssc__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) stylecsssc_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in stylecsssc__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = stylecsssc__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in stylecsssc__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up stylecsssc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		stylecsssc_text[stylecsssc_leng] = (yy_hold_char); \
		(yy_c_buf_p) = stylecsssc_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		stylecsssc_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int stylecsssc_get_lineno  (void)
{
        
    return stylecsssc_lineno;
}

/** Get the input stream.
 * 
 */
FILE *stylecsssc_get_in  (void)
{
        return stylecsssc_in;
}

/** Get the output stream.
 * 
 */
FILE *stylecsssc_get_out  (void)
{
        return stylecsssc_out;
}

/** Get the length of the current token.
 * 
 */
int stylecsssc_get_leng  (void)
{
        return stylecsssc_leng;
}

/** Get the current token.
 * 
 */

char *stylecsssc_get_text  (void)
{
        return stylecsssc_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void stylecsssc_set_lineno (int  line_number )
{
    
    stylecsssc_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see stylecsssc__switch_to_buffer
 */
void stylecsssc_set_in (FILE *  in_str )
{
        stylecsssc_in = in_str ;
}

void stylecsssc_set_out (FILE *  out_str )
{
        stylecsssc_out = out_str ;
}

int stylecsssc_get_debug  (void)
{
        return stylecsssc__flex_debug;
}

void stylecsssc_set_debug (int  bdebug )
{
        stylecsssc__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from stylecsssc_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    stylecsssc_in = stdin;
    stylecsssc_out = stdout;
#else
    stylecsssc_in = (FILE *) 0;
    stylecsssc_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * stylecsssc_lex_init()
     */
    return 0;
}

/* stylecsssc_lex_destroy is for both reentrant and non-reentrant scanners. */
int stylecsssc_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		stylecsssc__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		stylecsssc_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	stylecsssc_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * stylecsssc_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *stylecsssc_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *stylecsssc_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void stylecsssc_free (void * ptr )
{
	free( (char *) ptr );	/* see stylecsssc_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 216 "../../../lib/srchilite/stylecssscanner.ll"




